// <auto-generated />
namespace Цветочный_магазин.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updating_Type_Price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updating_Type_Price));
        
        string IMigrationMetadata.Id
        {
            get { return "202004141847392_Updating_Type_Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
